spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    flyway:
      enabled: true


app:
  ollama:
    baseUrl: ${OLLAMA_BASE_URL:http://localhost:11434}
    embedModel: ${OLLAMA_EMBED_MODEL:nomic-embed-text}
  similarity:
    threshold: ${SIM_THRESHOLD:0.95}